name: js_oa
description: 京师OA V1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # GetX
  get: ^4.3.8
  #网络
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.1
  dio_cookie_manager: ^2.0.0
  photo_view: ^0.12.0
  wechat_assets_picker: ^6.2.3
  wechat_camera_picker: ^2.5.0
  permission_handler: ^8.2.5
  #汉字转字母
  lpinyin: ^2.0.3
  #sticky header
  flutter_sticky_header: ^0.6.0
  #pull_to_refresh
  pull_to_refresh: ^2.0.0
  #腾讯IM_SDK
  tencent_im_sdk_plugin: 3.6.3
  #RTC实时通话
  tencent_trtc_cloud: ^1.2.9
  #腾讯TPNS推送
  tpns_flutter_plugin:
    git:
      url: "https://github.com/TencentCloud/TPNS-Flutter-Plugin"
      ref: "V1.1.5"
  #本地通知
  flutter_local_notifications: ^8.2.0
  #badge
  badges: ^2.0.1
  # 侧滑
  flutter_slidable: ^1.1.0
  # 图片加载框架
  cached_network_image: ^3.1.0+1
  # HUD + Toast https://github.com/nslog11/flutter_easyloading
  # flutter_easyloading: ^3.0.3
  # loading 动画组件 https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^5.1.0
  # loading 动画组件 https://pub.dev/packages/loading_animation_widget
  # loading_animation_widget: ^0.0.2+2
  #录音
  flutter_sound: ^8.4.2
  #视频播放
  video_player: ^2.2.10
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.8
  image_picker: ^0.8.4+4
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  # shared_preferences plugin util https://pub.dev/packages/sp_util
  sp_util: ^2.0.3
  # date_format: ^2.0.4
  # keframe 2.0.3
  # 震动
  vibration: ^1.7.4-nullsafety.0
  flutter_bugly: ^0.4.3
  # AD
  # 验证码输入框 https://pub.dev/packages/f_verification_box
  f_verification_box: ^0.0.2
  # 抖动Widget https://pub.dev/packages/f_shake_animation_widget
  f_shake_animation_widget: ^0.0.1
  # webview https://pub.dev/packages/flutter_webview_plugin
  webview_flutter: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # assets start
    - assets/images/mine/
    - assets/images/tab/
    - assets/images/workspace/
    - assets/images/login/
    - assets/images/contact/
    - assets/images/message/

    # HTML
    - assets/html/
  # assets end
  
  fonts:
    - family: AntdIcons
      fonts:
        - asset: assets/fonts/iconfont.ttf