name: js_oa
description: 京师OA V1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # GetX https://pub.flutter-io.cn/packages/get
  get: ^4.6.1
  # 网络 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.6
  # 网络缓存拦截 https://pub.flutter-io.cn/packages/dio_cache_interceptor
  dio_cache_interceptor: ^3.2.6
  # cookie管理 https://pub.flutter-io.cn/packages/dio_cookie_manager
  dio_cookie_manager: ^2.0.0
  # https://pub.flutter-io.cn/packages/photo_view
  photo_view: ^0.13.0
  # 微信图片选择器 https://pub.flutter-io.cn/packages/wechat_assets_picker
  wechat_assets_picker: ^7.1.0
  # 微信相机选择器 https://pub.flutter-io.cn/packages/wechat_camera_picker
  wechat_camera_picker: ^3.0.4
  # 权限管理器
  permission_handler: ^9.2.0
  # 汉字转字母 https://pub.flutter-io.cn/packages/lpinyin
  lpinyin: ^2.0.3
  # sticky header https://pub.flutter-io.cn/packages?q=flutter_sticky_header
  flutter_sticky_header: ^0.6.1
  # pull_to_refresh https://pub.flutter-io.cn/packages?q=pull_to_refresh
  pull_to_refresh: ^2.0.0
  # 腾讯IM_SDK https://pub.flutter-io.cn/packages/tencent_im_sdk_plugin
  # tencent_im_sdk_plugin: ^3.9.3
  tencent_im_sdk_plugin: ^3.6.3
  # RTC实时通话 https://pub.flutter-io.cn/packages/tencent_trtc_cloud
  # tencent_trtc_cloud: ^2.2.0
  tencent_trtc_cloud: ^1.2.9
  
  # 腾讯TPNS推送
  tpns_flutter_plugin:
    git:
      url: "https://github.com/TencentCloud/TPNS-Flutter-Plugin"
      ref: "V1.1.5"
  # 本地通知 https://pub.flutter-io.cn/packages?q=flutter_local_notifications
  flutter_local_notifications: ^9.4.0
  # badge https://pub.flutter-io.cn/packages/badges
  badges: ^2.0.2
  # 侧滑 https://pub.flutter-io.cn/packages/flutter_slidable
  flutter_slidable: ^1.2.0
  # 图片加载框架
  cached_network_image: ^3.2.0
  # HUD + Toast https://github.com/nslog11/flutter_easyloading
  # flutter_easyloading: ^3.0.3
  # loading 动画组件 https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^5.1.0
  # loading 动画组件 https://pub.dev/packages/loading_animation_widget
  # loading_animation_widget: ^0.0.2+2
  # 录音 https://pub.flutter-io.cn/packages/flutter_sound
  # flutter_sound: ^9.2.9
  flutter_sound: ^8.4.2
  # 视频播放 https://pub.flutter-io.cn/packages/video_player
  video_player: ^2.3.0
  # https://pub.flutter-io.cn/packages/video_thumbnail
  video_thumbnail: ^0.5.0
  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.9
  # https://pub.flutter-io.cn/packages/image_picker
  image_picker: ^0.8.5
  # https://pub.flutter-io.cn/packages/flutter_datetime_picker
  flutter_datetime_picker: ^1.5.1
  # https://pub.flutter-io.cn/packages/intl
  intl: ^0.17.0
  # shared_preferences plugin util https://pub.dev/packages/sp_util
  sp_util: ^2.0.3
  # date_format: ^2.0.4
  # keframe 2.0.3
  # 震动 https://pub.flutter-io.cn/packages/vibration/versions/1.7.4-nullsafety.0
  vibration: ^1.7.4-nullsafety.0
  # https://pub.flutter-io.cn/packages/flutter_bugly
  flutter_bugly: ^0.4.4
  # webview https://pub.flutter-io.cn/packages/flutter_webview_plugin
  webview_flutter: ^3.0.2
  # ------------------自定义------------------
  # 验证码输入框 https://pub.flutter-io.cn/packages/f_verification_box
  f_verification_box: ^0.0.2
  # 抖动Widget https://pub.flutter-io.cn/packages/f_shake_animation_widget
  f_shake_animation_widget: ^0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # assets start
    - assets/images/mine/
    - assets/images/tab/
    - assets/images/workspace/
    - assets/images/login/
    - assets/images/contact/
    - assets/images/message/

    # HTML
    - assets/html/
  # assets end
  
  fonts:
    - family: AntdIcons
      fonts:
        - asset: assets/fonts/iconfont.ttf